<?php

return array(

'identicon:title' => 'Identicon',
'identicon:avatar_upload_disabled' => 'While the Identicon image is used as your avatar the uploading/removal of a custom profile photo is disabled. If you want to upload and use your own custom avatar, please first disable the Identicon image to be used below.',
'identicon:identicon_yes' => 'Your account will now use the Identicon image.',
'identicon:identicon_no' => 'Your account will no longer use the Identicon image.',
'identicon:preference_checkbox' => 'Prefer your Identicon image over the default profile photo.',
'identicon:explanation' => 'An Identicon is an automatically generated user icon based on your email address. It is generated by an algorithm to be unique for each user.',

'identicon:group_identicon_yes' => 'The Identicon image will now be used as group photo.',
'identicon:group_identicon_no' => 'The Identicon image will no longer be used as group photo.',
'identicon:group_preference_checkbox' => 'Prefer the Identicon image over the default group photo.',
'identicon:group_explanation' => 'An Identicon is an automatically generated group icon based on the name of the group. It is generated by an algorithm to be unique for each group.'

);